### PR TITLE
WebClient. mcVersion returns fixed number. web client working.

### PR DESCRIPTION
**Pull request by nmingotti**
This little change makes this work:

    (WebClient httpGet:'http://www.google.com') content.

First time i do this, i hope I did well ;) 

bye

### CODE REVIEW

**Comment by jvuletich** [comment]
What symptoms do you experience without the fix? It seems to already work on on my system.
Thanks!

**Comment by nmingotti** [comment]
Hi Juan. The debugger opened on that method trying to make the http call. I guess it is the same issue stated as #171. I am running Cuis in Linux, Debian Stable. I can try to send you a picture or maybe induce the bug, freeze the image and try to send it to you. Tell me which you prefer.

**Comment by nmingotti** [comment]
Here is what i see without the patch:

image

**Comment by nmingotti** [comment]
In the new image it does not appear any more ... I am puzzled, i don't know if i can reproduce it, i know very little about git-github ;)

**Comment by nmingotti** [comment]
Ooook, i got it, my mistake ;) I tested with 'google.com', but i found the problem opening this:

     (WebClient httpGet:'http://localhost:3001/test1') content. 

Ignore it. I will investigate more. When I am ready I will try to pull again !

**Comment by nmingotti** [comment]
Ooook, i got it, my mistake ;) I tested with 'google.com', but i found the problem opening this:

     (WebClient httpGet:'http://localhost:3001/test1') content. 

Ignore it. I will investigate more. When I am ready I will try to pull again !

**Pull request closed without merging**
