### PR TITLE
Minor tweaks

### PR DESCRIPTION
**Pull request by pbella**

### CODE REVIEW

**Comment by jvuletich** [comment]
I removed AutoCompletter wrapping. It would break consistency with every other scrollable list in the system...

**Comment by pbella** [comment]
Juan,

I initially had the same concern and checked a few out.  What I noticed was
that *not* having the wrapping breaks compatibility with many other common
ones.  For example, when I go to the top method in the browser and arrow
up, it wraps to the bottom method and so on.  Doesn't this seems like a
good idea to you?  Why not instead track down those that don't wrap and
make them?

Thanks,
Phil


On Aug 2, 2017 2:33 PM, "Juan Vuletich" <notifications@github.com> wrote:

I removed AutoCompletter wrapping. It would break consistency with every
other scrollable list in the system...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/pull/123#issuecomment-319759353>,
or mute the thread

**Comment by pbella** [comment]
Just wanted to follow-up as I'm wondering if we're looking at the same
things since you're saying that nothing wraps.  Using a base image (3121) I
took a look at several tools that I use pretty heavily and here's what I
observed:

Things that wrap: world menu, file browser (file list in the top right
pane), system browser top panes, message browser top panes, package browser
top panes, changeset (right two top panes), process browser top panes.

Things that didn't wrap: file browser (directory hierarchy in the top left
pane), changeset (top left pane).

Thanks,
Phil


On Aug 2, 2017 3:54 PM, "Phil B" <pbpublist@gmail.com> wrote:

Juan,

I initially had the same concern and checked a few out.  What I noticed was
that *not* having the wrapping breaks compatibility with many other common
ones.  For example, when I go to the top method in the browser and arrow
up, it wraps to the bottom method and so on.  Doesn't this seems like a
good idea to you?  Why not instead track down those that don't wrap and
make them?

Thanks,
Phil


On Aug 2, 2017 2:33 PM, "Juan Vuletich" <notifications@github.com> wrote:

I removed AutoCompletter wrapping. It would break consistency with every
other scrollable list in the system...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/pull/123#issuecomment-319759353>,
or mute the thread

**Comment by jvuletich** [comment]
You are of course right, and I feel bad about what I did. I added it back. I apologize.

**Comment by pbella** [comment]
No worries... just wasn't sure we were looking at the same thing.

Thanks,
Phil

**Pull request merged**
