### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by len**
1. Some small fixes for Bag.

2. Changed String and SequenceableCollection|endsWith: and begingsWith: to answer true when the argument is empty. This is the most natural way to define it without creating contradictory behaviour, as the empty set is included in any set (included in the mathematical/logic sense).

3. I made a minimal Theme where the windows have border of width 1, and columns/rows in the Browser and other UI components are separated by only 1 pixel. This made evident some bugs in LayoutMorph, since a misalignment of 1 pixel was already very noticeable. You can also see some of the symptoms in the master branch on the default theme: take a SystemBrowser, go to some class with many methods and click a method category in order to make the scrollbar show in the method list (the last column), then take the right side of the window and slide it very slowly to resize the window, resize it just a few pixels slowly and you'll see how the scrollbar seems to change size... now this doesn't happen and my minimal theme looks nice too.

### CODE REVIEW

**Comment by len** [comment]
Added two more changesets. Please review.

**Comment by nachoba** [comment]
Luciano,
When I try to change a Theme, I get a >>doesNotUnderstand: #showTaskbar
The bug seems to be in the class side methods currentTheme: aTheme
Where CurrentTheme does not understand the showTaksbar message.
May be you tried to use useTaskbar?

CurrentTheme useTaskbar ifTrue: [w showTaskbar].

instead of

CurrentTheme showTaskbar ifTrue: [w showTaskbar].

Best
Nacho


*Lic. Ignacio Sniechowski, MBA*
*Prosavic SRL*

*Tel: (011) 4542-6714*

**Comment by len** [comment]
Oh, that's righ, thanks, i"ll fix it!

**Comment by jvuletich** [comment]
Just to let you all know, all this nice stuff by Luciano will be 
integrated as quickly as possible.

BTW, Luciano and I have been friends for a very long time, starting at 
the SUGAR Smalltalk group in the mid 90's. Welcome back to Smalltalk, 
and to our community Luciano!

Cheers,
Juan Vuletich

**Comment by garduino** [comment]
2015-11-16 21:58 GMT-03:00 Juan Vuletich <notifications@github.com>:

> Just to let you all know, all this nice stuff by Luciano will be
> integrated as quickly as possible.
>
> BTW, Luciano and I have been friends for a very long time, starting at
> the SUGAR Smalltalk group in the mid 90's. Welcome back to Smalltalk,
> and to our community Luciano!
>
>
+1 !!

I remember the name of Luciano form SqueakNOS project, I'm right?





> Cheers,
> Juan Vuletich
>
> On 15/11/2015 08:42 p.m., Luciano Notarfrancesco wrote:
> > Oh, that's righ, thanks, i"ll fix it!
> >
> > On Sun, Nov 15, 2015 at 12:11 PM, Ignacio Sniechowski <

**Comment by len** [comment]
Hi all,
Juan, thanks for the welcome! I love the simplicity and minimalism of
Cuis... it's exciting to see how nice this Smalltalk incarnation is
already, it's great to be able to contribute whatever I can to the project.

German, yes, SqueakNOS :)

Cheers!
Luciano

**Pull request merged**
