### PR TITLE
FileListWindow rm #update:  FileList use #triggerEvent: #updateButtonRow

### PR DESCRIPTION
**Pull request by dhnorton**

### CODE REVIEW

**Comment by jvuletich** [comment]
Hi Dan. This Pull Request seems to only include modifications to the Changes file. Maybe the real changes you intended were lost?

**Comment by dhnorton** [comment]
This may be a result of some cleanup I did. Can you apply 649057b and discard a0c8fe1? Thanks.

**Comment by jvuletich** [comment]
But 649057b includes changes to Cuis4.2-2829.changes. Can you provide regular changeset files?

**Comment by dhnorton** [comment]
On the way.

**Pull request closed without merging**
