### PR TITLE
Adapt Point immutable changes to backtick (i.e. `0@0`) syntax

### PR DESCRIPTION
**Pull request by pbella**
If this is acceptable, next I'll start migrating the 0@0 calls in the image...

### CODE REVIEW

**Comment by jvuletich** [comment]
I integrated most of the stuff in 3025, but not all. Immutable objects should never be modified, agreed. But that does not mean they need to be unique. Sometimes cloning an immutable object might be ok. WRT 3026, those optimizations should  be backed by profiling. Doing several extra tests before (for example) a sum might actually make stuff slower. Besides, comparing aPoint == `0@0` is almost guaranteed to fail. They are immutable, but not unique.

**Comment by pbella** [comment]
Sure, comparing to 0@0 would fail, but that's the whole point of migrating
calls to `0@0` (I.e. now that they are immutable, they can be made unique)
 I previously profiled the code (using the slower Point zero approach) and
any overhead to the #== checks was offset by the eliminated Point
creation.  I'd expect even better results with backticks syntax since that
eliminates some runtime overhead.  Even if only the core image/packages get
migrated, it still improves things overall (see my original post on the
thread and spreadsheet I published in the repo).  That said, if you still
don't approve, just let me know.

On Jan 15, 2017 12:12 PM, "Juan Vuletich" <notifications@github.com> wrote:

I integrated most of the stuff in 3025, but not all. Immutable objects
should never be modified, agreed. But that does not mean they need to be
unique. Sometimes cloning an immutable object might be ok. WRT 3026, those
optimizations should be backed by profiling. Doing several extra tests
before (for example) a sum might actually make stuff slower. Besides,
comparing aPoint == 0@0 is almost guaranteed to fail. They are immutable,
but not unique.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/pull/110#issuecomment-272708868>,
or mute the thread

**Comment by jvuletich** [comment]
Ok, but then let's find a way to make them unique. I doubt we'll succeed at that.

**Comment by pbella** [comment]
I must be missing something... Isn't that one of the main points of the
backtick syntax? I.e. that every call to `0@0` would return the same Point
instance?  Or did this feature go in a different direction that I haven't
caught on to yet?

On Jan 16, 2017 3:58 PM, "Juan Vuletich" <notifications@github.com> wrote:

Ok, but then let's find a way to make them unique. I doubt we'll succeed at
that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/pull/110#issuecomment-272960656>,
or mute the thread

**Comment by pbella** [comment]
I hit send too soon... If your concern is that we won't catch absolutely
every 0@0 call, don't worry about that too much.  The lion's share of the
calls that matter are in the optimization changes etc I've already
submitted and the base image.  Everything else is a bonus. (Really, I
profiled and measured it fairly extensively and unless you see an issue
with how I tested, I'm confident it will work)

**Comment by jvuletich** [comment]
someMethod
    a := `0@0`.
    b := `0@0`.
    ^ a == b

answers false. Check the bytecodes. Inspect the CompiledMethod. If necessary, do the profiling again. To do these kinds of changes one has to have a really good understanding of what is happening at the lower level. Otherwise it is better to make code simple and elegant.

What you had done before enforced uniqueness for 0@0, but not for any other values. Symbol is an implementation of uniqueness for Strings. Imagine doing that for all Float Points. The cost (both in memory and CPU) would be huge.

Besides, your implementation required a message send for each access to 0@0 (even if just to compare identity). With backticks these are just access to the method literal frame (i.e. free). So profiling would really be in order.

Anyway, our GC is pretty good. I don't think that avoiding a few Point creations would gain much. In any case, the real solution would be to implement ImmediatePoints at the VM level. It is possible to do that, given 64 bits OOPs.

**Pull request merged**
