### PR TITLE
RectangleLikeMorph>morphName:

### PR DESCRIPTION
**Pull request by dhnorton**
Because LayoutMorph has no labelString it is hard to keep track of the various morphs in a complex layout. This adds a name instance variable to RectangleLikeMorph along with methods morphName: and printOn:. You may want this to go into Morph instead of RectangleLikeMorph.

### CODE REVIEW

**Comment by hhzl** [comment]
@dhnorton Great that you have ported the TerseGuide. 

As far as code management is concerned, I suggest that you put the code into a package (extension ``*.pck.st``)  in [this folder](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/tree/master/Packages) rather than into a change set (extension ``*.cs.st``) to be included in the [core](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/tree/master/CoreUpdates). It can be managed with github whereas if you have it as a changeset then updates for the TerseGuide have to run through the [``CoreUpdates``](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/tree/master/CoreUpdates) folder. And there are more than 2000 files and github only displays the first 1000.

**Comment by dhnorton** [comment]
Great, I've been wondering how to do a package. I have a few others I want to propose and was not sure where they should reside. I'll put them in Packages directory. So to add and commit, etc. is it necessary to be in the Packages directory or in the Cuis-Smalltalk-Dev directory when I run git? (git and I don't git along yet :)

**Comment by hhzl** [comment]
Though you might not be terribly excited it pays off to learn git well. First read the help pages here.

And do your changes in a branch. After you have cloned the repository you may create a new branch and work there with

       git checkout -b myBranchName

The ``-b`` option creates the new branch. Afterwards you just do 

      git checkout myBranchName

After you have done your work you commit your changes. First you do

      git status 

to find out what has been changed. Then you add the files you want to be committed with

     git add theFileName

And then you commit

     git commit -m "the comment about my work"

And then you push the branch to github with 


      git push origin myBranchName

This assumes you have defined the name ``origin``. 

Then in the web gui of git you may create a pull request for myBranchName to be included in master of Cuis.

The nice thing about branches is that in case something goes wrong you may just delete the branch. Or switch to another branch. And you can work on things in parallel. 

You may have several branches branching off the master branch.

The whole thing might sound a bit overwhelming at the moment but there are very nice tutorials around. They are much better than what I have written here. And you can do it step by step.  

Github as a whole offers a lot in terms of version control.

**Comment by dhnorton** [comment]
@hhzl  yes, Github offers a lot in terms of version control. It has an impressive lineage (linusage?). Some of the things you mentioned I already did, but please check me out. I cloned Juan's repo on my Github account and made a branch of it on my PC (hope this terminology is correct). I added and committed the Terse Guide changes which were in a .pck file on my PC then from that directory did
  $git push origin master
  $git request-pull <version> <url of Juan's repo> 

Where <version> was from a previous commit about RectangleLikeMorph. The problem(?) is that the .pck file was not in the Packages directory on my PC but in the higher directory where the core stuff is. When I logged on to Github I saw that it combined the commit of this pull request with the earlier one for RectangleLikeMorph. I didn't expect that. I'm still very shaky on how to do things. When you're trying to get out of a hole, step one is to stop digging :) so how badly are things screwed up? Are you and I referring to different Packages directories? I notice that you refer to
   https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/tree/master/Packages

which I'm not familiar with. TIA.
 - Dan

**Comment by jvuletich** [comment]
Please email any and all code to the Cuis mail list, for discussion.
Thanks

**Pull request closed without merging**
